/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobencanto;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DropMode;
import javax.swing.JOptionPane;
import proyectobencanto.ProyectoBEncanto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gaby
 */
public class Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    int estado;
    public Cliente() throws SQLException {
        initComponents();
        estado = 0;
        generar(-123);
    }
    String sql,sql2;
    public static ResultSet resultados;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        IngresarNUevos = new javax.swing.JButton();
        Guardar2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(779, 340));

        IngresarNUevos.setText("IngresarNuevo");
        IngresarNUevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNUevosActionPerformed(evt);
            }
        });

        Guardar2.setText("Guardar");
        Guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar2ActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Cliente", "Apellidopaterno", "Apellidomaterno", "Nombre", "Saldo", "Direccion", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setMinWidth(100);
        }

        jLabel1.setText("NombreCliente:");

        Volver.setText("Salir");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(IngresarNUevos)
                                .addGap(38, 38, 38)
                                .addComponent(Volver)
                                .addGap(18, 18, 18)
                                .addComponent(Guardar2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(Buscar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarNUevos)
                    .addComponent(jButton3)
                    .addComponent(Volver)
                    .addComponent(Guardar2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        try {
        int id = Integer.parseInt(jTextField1.getText());
        sql = "select * from Cliente where idCliente = "+id+"";
        System.out.println(sql);
        generar(id);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "¡Ingresa un id numerico!");
        }
    }//GEN-LAST:event_BuscarActionPerformed
    private void generar(int valor) throws SQLException{
        int id_cliente;
        String ap, am ,nombre , telefono , direccion,query;
        float total;
        Connection con= ProyectoBEncanto.conectar();
        int val = 1;
        
        try {
            Statement comando = (Statement) con.createStatement(); 
            if(valor == -123)
                 query = "Select * from Cliente";
            else 
                query = "Select * from Cliente Where idCliente = "+valor+"";
            resultados = comando.executeQuery(query);
        } catch (SQLException e) {            
            System.out.println("\nError de lectura\n");
        }
        while(resultados.next()){
                
                try {   
                    
                    id_cliente = resultados.getInt("idCliente");
                    ap = resultados.getString("apellido_paterno");
                    am = resultados.getString("apellido_materno");
                    nombre = resultados.getString("nombre");
                    total = resultados.getFloat("saldo_restante");
                    telefono = resultados.getString("telefono");
                    direccion = resultados.getString("direccion");
                    if(valor == -123)
                        rescatar(id_cliente,ap,am,nombre,total,telefono,direccion);
                    else
                        jTable1.selectAll();
                    } catch (SQLException e) {
                        
                    System.out.println("\nError de lectura\n");
                }
        }
    }
    private void Guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar2ActionPerformed

        int rows , cols , folio = 0;
        rows = jTable1.getRowCount();
        cols = jTable1.getColumnCount();
        String nombres = null, apellidom = null, apellidop = null , 
                direccion = "" , telefono = "";
        float deuda = 0;
        try {
            ProyectoBEncanto.conectar();
        } catch (SQLException ex) {
            System.out.println("fallo conexion");
        }
        for(int x = 0 ; x < rows ; x ++){
            for(int y = 0 ; y < cols ; y ++){
                if(y == 0)
                folio = Integer.parseInt(
                    jTable1.getValueAt(x, y).toString());
                else if(y == 1)
                apellidop = jTable1.getValueAt(x, y).toString();
                else if(y == 2)
                apellidom = jTable1.getValueAt(x, y).toString();
                else if(y == 3)
                nombres = jTable1.getValueAt(x, y).toString();
                else if(y == 4){
                    deuda = Float.parseFloat(jTable1.getValueAt(x, y).
                        toString());
                }
                else if(y == 5)
                direccion = jTable1.getValueAt(x, y).toString();
                else if(y == 6)
                telefono = jTable1.getValueAt(x, y).toString();

            }

            sql ="INSERT INTO Cliente(idCliente,apellido_paterno"
            + ",apellido_materno,nombre,saldo_restante , telefono , direccion) "
            + "VALUES("+folio+",'"+apellidop+"',"
            + "'"+apellidom+"','"+nombres+"',"+deuda+", '"+telefono+"',"
                    + "'"+direccion+"')";
            sql2 ="UPDATE Cliente SET apellido_paterno = '"+apellidop+"',"
                    + "apellido_materno = '"+apellidom+"',nombre = '"+nombres+"'"
                    + ", direccion = '"+direccion+"', telefono = '"+telefono+"'"
                    + ", saldo_restante = "+deuda+" "
                    + "where idCliente = "+folio+"";
            
            try {
                ProyectoBEncanto.funcion(sql, sql2);
            } catch (SQLException ex) {
                
            }

        }
    }//GEN-LAST:event_Guardar2ActionPerformed

    private void IngresarNUevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNUevosActionPerformed
        DefaultTableModel  model = (DefaultTableModel)jTable1.getModel();
        int fila_select = model.getRowCount();
        int dato;
        if(fila_select > 0){
            dato = Integer.parseInt
                        (model.getValueAt(fila_select-1, 0).toString());
            dato += 1;
        }else
            dato = 1;
        rescatar(dato,"","","",0,"","");
    }//GEN-LAST:event_IngresarNUevosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = 0;
        try {
            row = jTable1.getSelectedRow();
            int value = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            sql = "DELETE FROM Cliente where idCliente = "+value+"";
            DefaultTableModel temp = (DefaultTableModel)jTable1.getModel();
            temp.removeRow(value-1);
            ProyectoBEncanto.funcion(sql,sql);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "¡Selecciona un elemento!");
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed
                                         
private void rescatar(int id , String ap , String am , String nombre,
        float total , String telefono , String direccion){
    DefaultTableModel  model = (DefaultTableModel)jTable1.getModel();

        int fila_select = model.getRowCount();
        int dato;
        Object[] fila = new Object [7];
        fila[0] = id;
        fila[1] = ap;
        fila[2] = am;
        fila[3] = nombre;
        fila[4] = total;
        fila[5] = telefono;
        fila[6] = direccion;
        model.addRow(fila);
        jTable1.setModel(model); 
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Guardar2;
    private javax.swing.JButton IngresarNUevos;
    private javax.swing.JButton Volver;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
